language: ruby
services:
  - docker

before_install:
  - docker build -t chipin/build .

script:
  - docker run --rm -v $TRAVIS_BUILD_DIR:/root/build chipin/build /bin/sh -c "source /root/.cargo/env; cd /root/build; make test"
  - docker run --rm -v $TRAVIS_BUILD_DIR:/root/build chipin/build /bin/sh -c "source /root/.cargo/env; cd /root/build; make"

deploy:
  provider: releases
  api_key:
    secure: "Y73ArImfPC9bFIERmeT3rCrvQ5spJ+MKUTc+f81+Dentr4NYm1R52uXBlmD6A9eg0m+VRBPI7Z7xDjerRAqODd5YwczDFuAsPj4zl8jVSoVAt37e/ypWej4TcW9yePlATaFHPAD/v0LQI03il6EnhG5yRiAPP8xT0bpjwm5ZUZ/ixDyPPCKZTN7sFhRGfs9z11DGjQxLD5pLgqqb9ZRo9jppFU6vjxjA+h/t8rIoxBsGosHiDgXV+eQusZrf2jxmDS4twrvmvGfXsjCbs53ZlcZdRcrKNsDdSVYMo3JRAxcz+TnaxptGroT3cAvbSUSUEwC7BkvyyDhP8Ru3dtwVKhSwFG4+fihA9m1WffvuZoJhgBonDCsbbBO3VirfHl324Vq12ZW+dV9pXO25OUPmQbG0kMZMy5TnlrRVW+o4jUw8SuR+SpsZXVNuHsT+vC073IId5XI21RAs1iXfXz5QiqvC2J3LXNYd7Q19cqnEYsH/shyq4WldV1EwIz8XcLJuQ3rcqiPBWnTmw6RpKSydo0azKNsE2BkmtqUiZfTs2aRBdwtnm49TwjW1enuVuICnAMcBLBSU9dvDYlEpGxLnB4+8AQTK6tH11Ir4cpooElXYYjA6ftw+sfmxmjG1Gu6I/zW9nGYkTFPVcQrQu4pU+NTUMFkeTmpy+CxeMQqseHQ="
  file: "chipin_auth_plug.so"
  skip_cleanup: true
  on:
    tags: true
