name: Build Test
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        env:
          TRAVIS_BUILD_DIR: ${{ github.workspace }}
        run: |
          docker build -t chipin/build .
          docker run --rm -v $TRAVIS_BUILD_DIR:/root/build chipin/build /bin/sh -c "source /root/.cargo/env; cd /root/build; make test"
          docker run --rm -v $TRAVIS_BUILD_DIR:/root/build chipin/build /bin/sh -c "source /root/.cargo/env; cd /root/build; make"
