name: release apps

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  push_to_github:
    name: Release artifacts to github
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build
        env:
          TRAVIS_BUILD_DIR: ${{ github.workspace }}
        run: |
          docker build -t chipin/build .
          docker run --rm -v $TRAVIS_BUILD_DIR:/root/build chipin/build /bin/sh -c "source /root/.cargo/env; cd /root/build; make test"
          docker run --rm -v $TRAVIS_BUILD_DIR:/root/build chipin/build /bin/sh -c "source /root/.cargo/env; cd /root/build; make"

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: chipin_auth_plug.so
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "${{env.TAG_VALUE}}"
          allowUpdates: true
